### ISSUE TITLE
Apparent crash during startup (Mod is by itself)

### ISSUE THREAD

**Issue by Yipeekiyaay** [AnOpenSauceDev/Odometer#3]
For some reason, the mod seems to crashing all by itself:

[crash.txt](https://github.com/AnOpenSauceDev/Odometer/files/11503697/crash.txt)

Minecraft is not generating the crash-logs for some reason.

I hope I'm not just commiting a dumb mistake here... The game also seems to run normally one version down.

**Comment by AnOpenSauceDev** [comment]
looks like I forgot to go back and make sure that 1.19.2 actually worked, it's erroring out thanks to the differences in 1.19.4 and 1.19.2's code (damage is now DamageTypes, which seems to have broken it)

**Comment by AnOpenSauceDev** [comment]
had some time to work on it, and https://github.com/AnOpenSauceDev/Odometer/commit/eaac630408f9202b958edc1502304a4f54dc16eb fixes this
